program_id = 2736
instrument = 'nirspec'

redshift = 0.0
mast_cube_prefix = 'jw02736-o007'

# see https://www.stsci.edu/jwst/phase2-public/2736.pdf
sci_obs = 7

target_name = '06355'

data_dir = '2736/data_sets/pipeline_1.8.4/007/'
product_name = 'o007_pipeline_1.8.4'
