target_name = 'XID2028'

program_id = 1335
instrument = 'nirspec_ifu'

redshift = 1.593 # Brusa 2018

# For XID2028, see https://www.stsci.edu/jwst/phase2-public/1335.pdf
obs = 4

# actions = ['download_all', 'run_pipeline']
actions = ['run_pipeline',]
# actions = ['extract_1D',]
# actions = ['run_badass',]

pipeline.multiprocess = false
pipeline.nprocesses = 4
pipeline.stage2.steps.cube_build.weighting = 'emsm'

extract.aperture_name = 'aperture'
extract.aperture_radius = 0.5 # arcsecs
# extract.aperture_radius = 'psf'


badass.target = 'cube'
# badass.target = '1D' # or 'cube'
# badass.line = 'ArVI_4'
# badass.options_file = 'ir_options1.py'
badass.options_file = 'region5_options.py'
# badass.wave_range = 2000
