target_name = 'XID2028'

program_id = 1335
instrument = 'miri'

redshift = 1.593 # Brusa 2018

# For XID2028, see https://www.stsci.edu/jwst/phase2-public/1335.pdf
sci_obs = 5
bkgd_obs = 12

actions = ['download_uncal', 'run_pipeline']
# actions = ['extract_1D',]
# actions = ['run_badass',]

pipeline.multiprocess = true
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 3.0 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'ArVI_4'
badass.options_file = 'ir_options1.py'
badass.wave_range = 2000
