target_name = 'NGC_4151'

program_id = 1364
instrument = 'nirspec_ifu'

redshift = 0.003262

# For NGC 4151, see https://www.stsci.edu/jwst/phase2-public/1364.pdf
obs = 1

actions = ['download_all', 'run_pipeline',]
# actions = ['run_pipeline',]

pipeline.multiprocess = true
pipeline.nprocesses = 4
