target_name = 'IIZw096'

program_id = 1328
instrument = 'miri'

redshift = 0.036 # Inami+22

# For IIZw096, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
sci_obs = 33
bkgd_obs = 34

# actions = ['download', 'pipeline', 'extract_1D']
# actions = ['extract_1D',]
actions = ['run_badass',]

pipeline.multiprocess = true
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 1.08 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'NeVI_7'
badass.options_file = 'ir_options1.py'
badass.wave_range = 40000
