program_id = 1328
instrument = 'nirspec'

redshift = 0.01627

# For NGC 7469, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
sci_obs = 18

data_dir = '1328/data_sets/pipeline_1.8.5/nirspec_ifu/ngc_7469/'
product_name = 'ngc7469_pipeline_1.8.5'
