target_name = 'NGC_7469'

program_id = 1328
instrument = 'nirspec_ifu'

redshift = 0.01627

# For NGC 7469, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
obs = 18

# actions = ['download_all', 'run_pipeline',]
# actions = ['run_pipeline',]
actions = ['extract_1D']

pipeline.multiprocess = true
pipeline.nprocesses = 4

extract.aperture_name = 'aperture'
# extract.aperture_radius = 1.08 # arcsecs
extract.aperture_radius = 0.4 # arcsecs
