target_name = 'VV114'

program_id = 1328
instrument = 'miri'

redshift = 0.02 # Evans+22

# For VV 114, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
sci_obs = 20
bkgd_obs = 21

# actions = ['download', 'pipeline', 'extract_1D']
# actions = ['extract_1D',]
actions = ['run_badass',]

pipeline.multiprocess = true
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 1.08 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'FeVII_7'
badass.options_file = 'ir_options1.py'
badass.wave_range = 40000
