product_name = 'pipeline_1.14.0'

[target]
name = 'J1201'
program_id = 1983
# redshift = 0.003251394 # SDSS
redshift = 0.003542211 # from Pa A peak

[instrument]
name = 'nirspec_ifu'
# For J1201, see https://www.stsci.edu/jwst/phase2-public/1983.pdf
obs = 2

[[action]]
name = 'download'

[[action]]
name = 'pipeline'
multiprocess = false
# stage1.flag_snowballs = true
# stage1.clean_rates = true
# stage2.steps.cube_build.weighting = 'emsm'

# JWST Pipeline version >= 1.12.0:
# stage3.steps.cube_build.scalexy = 0.05 # arcsecs

# JWST Pipeline version <= 1.11.4:
# stage3.steps.cube_build.scale1 = 0.05 # arcsecs
# stage3.steps.cube_build.scale2 = 0.05 # arcsecs

# Example options
# spec3.outlier_detection.skip = true
# spec3.extract_1d.center_xy = (29, 26)
# spec3.outlier_detection.threshold_percent = 90
