target_name = 'NGC_7469'

program_id = 1328
instrument = 'miri'

redshift = 0.01627
mast_cube_prefix = 'jw01328-o015_t014_miri'

# For NGC 7469, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
sci_obs = 15
bkgd_obs = 16

# actions = ['download_uncal', 'run_pipeline', 'extract_1D']
actions = ['run_badass',]

pipeline.multiprocess = true
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 1.08 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'MgV_5'
badass.options_file = 'ir_options1.py'
