target_name = 'VV114'

program_id = 1328
instrument = 'nirspec_ifu'

redshift = 0.02 # Evans+22

# For VV114, see https://www.stsci.edu/jwst/phase2-public/1328.pdf
obs = 23

# actions = ['download_all',]
# actions = ['run_pipeline',]
actions = ['extract_1D']

pipeline.multiprocess = true
pipeline.nprocesses = 4

extract.aperture_name = 'aperture_sum'
# extract.aperture_radius = 1.08 # arcsecs
extract.aperture_radius = 0.4 # arcsecs
