target_name = 'NGC_7319'

program_id = 2732
instrument = 'miri'
redshift = 0.022823

# For NGC 7319, see see https://www.stsci.edu/jwst/phase2-public/2732.pdf
sci_obs = 4
bkgd_obs = 5

actions = ['download_uncal']
# actions = ['run_pipeline',]
# actions = ['extract_1D',]
# actions = ['run_badass',]
# actions = ['combine_results',]

pipeline.multiprocess = false
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 1.0 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'NeV_24'
badass.options_file = 'ir_options1.py'
badass.wave_range = 2000
