target_name = 'SGAS_1226'

program_id = 1355
instrument = 'miri'

redshift = 0.43

# For SGAS_1226, see https://www.stsci.edu/jwst/phase2-public/1355.pdf
sci_obs = 5
bkgd_obs = 6

# actions = ['download_uncal', 'run_pipeline']
actions = ['extract_1D']

pipeline.multiprocess = true
pipeline.nprocesses = 4
pipeline.residual_fringe_correct = true
pipeline.include_bkgd = true

extract.aperture_name = 'aperture'
extract.aperture_radius = 1.08 # arcsecs

badass.target = '1D' # or 'cube'
badass.line = 'NeV_24'
badass.options_file = 'ir_options1.py'
