product_name = 'pipeline_1.20.2_vanilla'
output_dir = 'src/daedalus/testing/test_out/'
crds_cache = 'src/daedalus/testing/crds_cache/'

[target]
name = 'NGC_7469'
program = 1328
redshift = 0.01627

[target.instrument]
name = 'nirspec_ifu'
obs = 18

[[actions]]
name = 'download'

[[actions]]
name = 'pipeline'
